### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-isochrone#11]
Following up on the ambiguous-yet-earnest #9,  I looked at the responses to [the looped directions API call](https://github.com/mapbox/mapbox-isochrone/blob/master/dist/app.js#L154). I logged the error associated with the call and found this:

`"message":"Too Many Requests"`

@peterqliu did the platform team feel this module was hammering the API too hard and lock usage down? Any [single call](https://api.mapbox.com/directions-matrix/v1/mapbox/driving/-121.4738,38.6194;-121.7011,38.5175;-121.7011,38.5239;-121.7011,38.5302;-121.7011,38.5366;-121.7011,38.5430;-121.7011,38.5493;-121.7011,38.5557;-121.7011,38.5621;-121.7011,38.5684;-121.7011,38.5748;-121.7011,38.5812;-121.7011,38.5876;-121.6930,38.5175;-121.6930,38.5239;-121.6930,38.5302;-121.6930,38.5366;-121.6930,38.5430;-121.6930,38.5493;-121.6930,38.5557;-121.6930,38.5621;-121.6930,38.5684;-121.6930,38.5748;-121.6930,38.5812;-121.6930,38.5876?sources=0&destinations=all&access_token=pk.eyJ1IjoiZmFyYWRheTIiLCJhIjoiY2pmN2l4b29yMGIyeDQ0cDRmZHJkdm40dSJ9.PUbiweL5u3zUQm8UP5Zv1g) still works fine.

**Comment by peterqliu** [comment]
per chat, we figured out this was due to rate-limiting

**Comment by wboykinm** [comment]
For future reference, I was able to get around this error to a limited extent by 

1. Playing with the `resolution` param
2. Adding a modest (500-2000ms) `setTimeout()` to [the request loop](https://github.com/mapbox/mapbox-isochrone/blob/master/isochrone.js#L132)

This would be better-tuneable as a node script, but that's a whole other can of worms.

**Comment by peterqliu** [comment]
👍 thanks for writing out those tips. I just merged a PR that addresses/alleviates some of these relevant troubles https://github.com/mapbox/mapbox-isochrone/pull/14
