### ISSUE TITLE
[Question] Make OSRM / Directions endpoint configurable 

### ISSUE THREAD

**Issue by sweco-semtne** [mapbox/mapbox-isochrone#3]
Is it possible to make the matrix endpoint configurable?

**Comment by peterqliu** [comment]
@sweco-semtne yes, and it would be easier if the other endpoints followed the same input/output format. Endpoint logic is [here](https://github.com/mapbox/mapbox-isochrone/blob/master/isochrone.js#L152).

**Comment by peterqliu** [comment]
Closing, until we get a better sense of what custom endpoints would look like
