### ISSUE TITLE
Conrec License

### ISSUE THREAD

**Issue by henningko** [mapbox/mapbox-isochrone#7]
Awesome plugin, but looking through the code we realized that conrec.js is not published under an MIT license, and is based on implementations that are fairly restrictive in their terms (see https://github.com/mapbox/mapbox-isochrone/blob/master/lib/conrec.js).

If we are only interested in distinct polygons for specific drive times, is there a way to do it without relying on Conrec?

**Comment by peterqliu** [comment]
@henningko thanks for the heads up! Definitely open to using another library-- I see that D3 has a [contouring method](https://bl.ocks.org/mbostock/4241134) that polygonizes in a similar manner.

**Comment by henningko** [comment]
Actually reached out to the authors of CONREC, and they assured it was ok to use. Maybe I can direct them here to clarify for everyone :-)

**Comment by henningko** [comment]
See:
https://github.com/nyue/conrec

for Nicholas Yue's C implementation.
